#!/bin/bash
#
#   Author:  kilrainebc
#   Version: 1.0
#   Description: Script to configure fresh Proxmox install 

# Source functions libraries
# shellcheck disable=SC1091
source ./lib/sources.bash
source ./lib/software.bash
source ./lib/storage.bash
#source ./lib/network.bash
#source ./lib/user.bash
source ./lib/other.bash

if [[ $1 -eq "uninstall" ]]; then
  sources_undo
  uninstall_software_config
  clean_storage_config
  remove_other_config
fi

if [[ $1 -eq "apply" ]]; then
  sources_config
  software_config
  storage_config
  #netowrk_config
  #user_config
  other_config
fi


